mapviz:
  ros__parameters:
    capture_directory: "~"
    fixed_frame: local_xy
    target_frame: <none>
    fix_orientation: false
    rotate_90: false
    enable_antialiasing: true
    show_displays: true
    show_status_bar: true
    show_capture_tools: true
    window_width: 1219
    window_height: 600
    view_scale: 47.4682999
    offset_x: 986.523132
    offset_y: 18340.3848
    use_latest_transforms: true
    background: "#a0a0a4"
    image_transport: raw
    displays:
    - type: mapviz_plugins/tile_map
      name: new display
      config:
        visible: true
        collapsed: false
        custom_sources:
          - base_url: http://localhost:8080/wmts/gm_layer/gm_grid/{level}/{x}/{y}.png
            max_zoom: 17
            name: custommaps
            type: wmts
        bing_api_key: ""
        source: custommaps
    # displays:
    #   - name: "Offline Map"
    #     type: "mapviz_plugins/TileMap"
    #     config:
    #       custom_sources:
    #         - name: "offlinesource"
    #           type: "wmts"
    #           base_url: "http://localhost:8080/wmts/gm_layer/gm_grid/{level}/{x}/{y}.png"
    #           max_zoom: "17"
    #           is_custom: true
    #       source: "offlinesource"
    #       bing_api_key: ""